In [6]:
import numpy as np
import pandas as pd

dataFile = pd.read_csv('pca_test_dhenge2kumar1.csv')
expNames = dataFile['Experiments']
dataFile_edit = dataFile.drop(['Sr No','Screw Configuration','Experiments','Liq add position'],axis=1)

munDim = {
    "OD" : 16,
    "L/D": 25,
    "Ae" : 23.56,
    "Ls" : 3,
    "As" : 34.37,
    "Ll" : 10,
    "Tdpm" : 1.18,
    "Bdpm" : 0.65,
    "Tdlm" : 1.52,
    "Bdlm" : 0.57,
    "Lspce" : 1,
    "Ac" : 201,
    "Vspce" : 1,
    "Vlpce" : 2,
    "Vke" : 0.3,
    "Vice" : 0.75,
}


In [7]:
l_total_mun = munDim["OD"]*munDim["L/D"]
print(l_total_mun)

400


In [8]:
l_eff_mun = l_total_mun-2*16*munDim["Lspce"]
At_mun = 2 * munDim["Ac"] - munDim["Ae"]
v_max_mun = l_eff_mun*At_mun
v_shaft_mun = (l_eff_mun*munDim["As"])
v_elem_mun_sc3 = (2*munDim["Vlpce"]+18*munDim["Vspce"])
v_free_mun_sc3 = v_max_mun - v_shaft_mun - v_elem_mun_sc3
print(v_free_mun_sc3)
mfr = np.array([2.19,6,6.61]) / 3600 # flow rate kg/s
rho_bulk = 500
D=np.array([0.011,0.016,0.024])
rpm = np.array([482,600,327])*np.pi/30 # convert rpm to radians per second 
denom = rho_bulk*np.multiply(rpm,np.power(D,3))
pfn = np.divide(mfr,denom) 
print(pfn)

126595.76000000001
[0.01810998 0.01295206 0.00775745]


In [9]:
ae_16 = munDim["Ae"]
ae_16_sqrt = np.sqrt(ae_16)
ae_11_scaled = ae_16_sqrt * 11 / 16
ae_24_scaled = ae_16_sqrt * 24 / 16
ae_11 = ae_11_scaled ** 2
ae_24 = ae_24_scaled ** 2
ae_array = np.array([ae_11,ae_16,ae_24]) / 1e6
print(ae_array) 

[1.11357812e-05 2.35600000e-05 5.30100000e-05]


In [10]:
F1 = np.divide(ae_array,np.power(D,2))
print(F1)
F2 = np.ones((1,len(F1)))
print(F2)
mrt = [38,35,20]
vp = np.divide(16*.04,mrt)
print(vp)
F3num = 2*np.pi*vp
F3dem = rpm*0.016
F3 = np.divide(F3num,F3dem)
print(F3)
fill = np.divide(pfn,np.multiply(F1,np.multiply(F2,F3)))
print(fill)

[0.09203125 0.09203125 0.09203125]
[[1. 1. 1.]]
[0.01684211 0.01828571 0.032     ]
[0.13103298 0.11428571 0.36697248]
[[1.50176497 1.23143548 0.22969421]]
